Add Form component
thangngoc89/bs-ant-design pull request #17
Opened 2018-10-05 13:03 UTC by VonderVuflya

2018-10-07 23:36 UTC, luisfcofv requested changes

2018-10-07 23:36 UTC, luisfcofv commented on package.json
> +  "version": "2.0.1",
This is bumped by npm automatically. Please revert this.

2018-10-07 23:37 UTC, luisfcofv commented on src/Antd_Form.re
> +let wrapper = (~component, ~make', ~props, ~children) => {
is this needed?

2018-10-10 11:09 UTC, VonderVuflya reviewed
Fix version and del wrapper

2018-10-14 14:14 UTC, luisfcofv approved these changes

2018-10-14 14:15 UTC, merged